name: Test

"on":
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello ubuntu
  test-windows:
    runs-on: windows-latest
    steps:
      - run: echo hello windows
